/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	crdv1 "github.com/kylin/kylin-node-controller/pkg/apis/crd/v1"
	versioned "github.com/kylin/kylin-node-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kylin/kylin-node-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/kylin/kylin-node-controller/pkg/client/listers/crd/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KylinNodeInformer provides access to a shared informer and lister for
// KylinNodes.
type KylinNodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KylinNodeLister
}

type kylinNodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKylinNodeInformer constructs a new informer for KylinNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKylinNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKylinNodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKylinNodeInformer constructs a new informer for KylinNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKylinNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().KylinNodes(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CrdV1().KylinNodes(namespace).Watch(options)
			},
		},
		&crdv1.KylinNode{},
		resyncPeriod,
		indexers,
	)
}

func (f *kylinNodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKylinNodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kylinNodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&crdv1.KylinNode{}, f.defaultInformer)
}

func (f *kylinNodeInformer) Lister() v1.KylinNodeLister {
	return v1.NewKylinNodeLister(f.Informer().GetIndexer())
}
