/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	crdv1 "github.com/kylin/kylin-node-controller/pkg/apis/crd/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKylinNodes implements KylinNodeInterface
type FakeKylinNodes struct {
	Fake *FakeCrdV1
	ns   string
}

var kylinnodesResource = schema.GroupVersionResource{Group: "crd.k8s.io", Version: "v1", Resource: "kylinnodes"}

var kylinnodesKind = schema.GroupVersionKind{Group: "crd.k8s.io", Version: "v1", Kind: "KylinNode"}

// Get takes name of the kylinNode, and returns the corresponding kylinNode object, and an error if there is any.
func (c *FakeKylinNodes) Get(name string, options v1.GetOptions) (result *crdv1.KylinNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kylinnodesResource, c.ns, name), &crdv1.KylinNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdv1.KylinNode), err
}

// List takes label and field selectors, and returns the list of KylinNodes that match those selectors.
func (c *FakeKylinNodes) List(opts v1.ListOptions) (result *crdv1.KylinNodeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kylinnodesResource, kylinnodesKind, c.ns, opts), &crdv1.KylinNodeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &crdv1.KylinNodeList{ListMeta: obj.(*crdv1.KylinNodeList).ListMeta}
	for _, item := range obj.(*crdv1.KylinNodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kylinNodes.
func (c *FakeKylinNodes) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kylinnodesResource, c.ns, opts))

}

// Create takes the representation of a kylinNode and creates it.  Returns the server's representation of the kylinNode, and an error, if there is any.
func (c *FakeKylinNodes) Create(kylinNode *crdv1.KylinNode) (result *crdv1.KylinNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kylinnodesResource, c.ns, kylinNode), &crdv1.KylinNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdv1.KylinNode), err
}

// Update takes the representation of a kylinNode and updates it. Returns the server's representation of the kylinNode, and an error, if there is any.
func (c *FakeKylinNodes) Update(kylinNode *crdv1.KylinNode) (result *crdv1.KylinNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kylinnodesResource, c.ns, kylinNode), &crdv1.KylinNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdv1.KylinNode), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKylinNodes) UpdateStatus(kylinNode *crdv1.KylinNode) (*crdv1.KylinNode, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kylinnodesResource, "status", c.ns, kylinNode), &crdv1.KylinNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdv1.KylinNode), err
}

// Delete takes name of the kylinNode and deletes it. Returns an error if one occurs.
func (c *FakeKylinNodes) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kylinnodesResource, c.ns, name), &crdv1.KylinNode{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKylinNodes) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kylinnodesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &crdv1.KylinNodeList{})
	return err
}

// Patch applies the patch and returns the patched kylinNode.
func (c *FakeKylinNodes) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *crdv1.KylinNode, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kylinnodesResource, c.ns, name, pt, data, subresources...), &crdv1.KylinNode{})

	if obj == nil {
		return nil, err
	}
	return obj.(*crdv1.KylinNode), err
}
